# Generated by Django 5.1.3 on 2024-11-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Models',
            new_name='Topic',
        ),
    ]
